pod 'SAMGradientView'
pod 'iOS-color-wheel'
pod 'ASValueTrackingSlider'
pod 'BEMAnalogClock'
pod 'VBFPopFlatButton'
pod 'DKCircleButton'
pod 'CHCircleGaugeView'
pod 'NYSegmentedControl'
pod 'LLSimpleCamera'

